# Generated by Django 5.2.17 on 2026-09-17 03:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(default="email", max_length=16)),
                ("template_key", models.CharField(max_length=64)),
                ("payload_ciphertext", models.BinaryField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("sending", "Отправляется"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка, будет повтор"),
                            ("dead", "Отброшено после всех попыток"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.SmallIntegerField(default=0)),
                ("max_attempts", models.SmallIntegerField(default=5)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, default="", max_length=64)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_messages",
                        to="accounts.useremail",
                    ),
                ),
            ],
            options={
                "verbose_name": "исходящее сообщение",
                "verbose_name_plural": "исходящие сообщения",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "pending")),
                        fields=["next_attempt_at"],
                        name="outbox_ready_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["pending", "sending", "sent", "failed", "dead"],
                            )
                        ),
                        name="outbox_status_valid",
                    )
                ],
            },
        ),
    ]
