# Generated by Django 5.2.17 on 2026-09-17 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="публичный идентификатор",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="логин")),
                (
                    "username_normalized",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buyer", "Покупатель"),
                            ("admin", "Администратор"),
                            ("owner", "Владелец"),
                        ],
                        default="buyer",
                        max_length=16,
                        verbose_name="роль",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения почты"),
                            ("active", "Активен"),
                            ("blocked", "Заблокирован"),
                            ("anonymized", "Обезличен"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="состояние",
                    ),
                ),
                (
                    "anonymized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="обезличен"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменён"),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["buyer", "admin", "owner"])),
                        name="user_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["pending", "active", "blocked", "anonymized"],
                            )
                        ),
                        name="user_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("username_normalized", ""), _negated=True),
                        name="user_username_normalized_present",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_ciphertext",
                    models.BinaryField(verbose_name="зашифрованный адрес"),
                ),
                (
                    "email_bidx",
                    models.BinaryField(max_length=32, verbose_name="слепой индекс"),
                ),
                (
                    "key_version",
                    models.SmallIntegerField(default=1, verbose_name="версия ключа"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="основной"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="подтверждён"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="подтверждён в"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="истекает"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес почты",
                "verbose_name_plural": "адреса почты",
            },
        ),
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("email_verify", "Подтверждение почты"),
                            ("password_reset", "Сброс пароля"),
                        ],
                        max_length=24,
                    ),
                ),
                ("token_hash", models.BinaryField(max_length=32)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.SmallIntegerField(default=0)),
                ("max_attempts", models.SmallIntegerField(default=5)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="accounts.useremail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "токен подтверждения",
                "verbose_name_plural": "токены подтверждения",
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("registered", "Регистрация"),
                            ("email_verified", "Почта подтверждена"),
                            ("login_ok", "Успешный вход"),
                            ("login_failed", "Неудачный вход"),
                            ("logout", "Выход"),
                            ("password_changed", "Пароль изменён"),
                            ("password_reset_requested", "Запрошен сброс пароля"),
                            ("role_changed", "Роль изменена"),
                            ("user_blocked", "Пользователь заблокирован"),
                            ("user_anonymized", "Учётная запись обезличена"),
                        ],
                        max_length=48,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "событие безопасности",
                "verbose_name_plural": "события безопасности",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="event_by_user_idx"
                    ),
                    models.Index(
                        condition=models.Q(("event_type", "login_failed")),
                        fields=["ip", "-created_at"],
                        name="failed_login_by_ip_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_key",
                    models.CharField(max_length=64, verbose_name="документ"),
                ),
                (
                    "document_version",
                    models.CharField(max_length=32, verbose_name="версия"),
                ),
                ("document_hash", models.BinaryField(max_length=32)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="отозвано"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "согласие",
                "verbose_name_plural": "согласия",
                "indexes": [
                    models.Index(
                        fields=["user", "document_key"], name="consent_lookup_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="useremail",
            index=models.Index(
                condition=models.Q(("is_verified", False)),
                fields=["expires_at"],
                name="pending_email_expiry_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="useremail",
            constraint=models.UniqueConstraint(
                fields=("email_bidx",), name="email_bidx_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="useremail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("user",),
                name="one_primary_email_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="useremail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_verified", False)),
                fields=("user",),
                name="one_pending_email_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="useremail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_verified", True), ("verified_at__isnull", False)),
                    models.Q(("is_verified", False), ("verified_at__isnull", True)),
                    _connector="OR",
                ),
                name="verified_requires_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationtoken",
            index=models.Index(
                condition=models.Q(("consumed_at__isnull", True)),
                fields=["user", "purpose"],
                name="active_token_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationtoken",
            constraint=models.UniqueConstraint(
                fields=("token_hash",), name="token_hash_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationtoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose__in", ["email_verify", "password_reset"])),
                name="token_purpose_valid",
            ),
        ),
    ]
